version: '3.3'

services:
  db:
    image: postgres:13
    container_name: auth_db

    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://auth_db/auth_db -user=postgres -password=123123 -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db